controllers:
    resource: '../../src/Controller/'
    type: annotation
    prefix: '/{_locale}'
    requirements:
        _locale: '%app_locales_regex%'

kernel:
    resource: '../../src/Kernel.php'
    type: annotation
